//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIsEDM.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compra()
        {
            this.Fk_DetalleCompra = new HashSet<DetalleCompra>();
        }
    
        public int IdCompra { get; set; }
        public string Codigo { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public int ProveedorIdProveedor { get; set; }
        public int EmpleadoIdEmpleado { get; set; }
    
        public virtual Proveedor Fk_Proveedor { get; set; }
        public virtual Empleado Fk_Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCompra> Fk_DetalleCompra { get; set; }
    }
}
