//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIsEDM.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBVentaContainer : DbContext
    {
        public DBVentaContainer()
            : base("name=DBVentaContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Venta> Venta { get; set; }
        public virtual DbSet<Datos> Datos { get; set; }
        public virtual DbSet<DetalleCompra> DetalleCompra { get; set; }
        public virtual DbSet<Compra> Compra { get; set; }
        public virtual DbSet<DetalleVenta> DetalleVenta { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<Modelo> Modelo { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
    
        public virtual int BusquedaCategoria1(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaCategoria1", descripcionParameter);
        }
    
        public virtual int BusquedaCliente1(string nombre, string apellido)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaCliente1", nombreParameter, apellidoParameter);
        }
    
        public virtual int BusquedaEmpleado1(string nombre, string apellido)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaEmpleado1", nombreParameter, apellidoParameter);
        }
    
        public virtual int BusquedaMarca1(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaMarca1", descripcionParameter);
        }
    
        public virtual int BusquedaModelo1(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaModelo1", descripcionParameter);
        }
    
        public virtual int BusquedaProducto1(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaProducto1", descripcionParameter);
        }
    
        public virtual int BusquedaProveedor1(string nombre, string apellido)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaProveedor1", nombreParameter, apellidoParameter);
        }
    
        public virtual int ListaCategoria1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaCategoria1");
        }
    
        public virtual int ListaClientes1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaClientes1");
        }
    
        public virtual int ListaEmpledos1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaEmpledos1");
        }
    
        public virtual int ListaMarca1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaMarca1");
        }
    
        public virtual int ListaModelo1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaModelo1");
        }
    
        public virtual int ListaProductos1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaProductos1");
        }
    
        public virtual int ListaProveedores1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaProveedores1");
        }
    
        public virtual int BusquedaCategoria(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaCategoria", descripcionParameter);
        }
    
        public virtual int BusquedaCliente(string nombre, string apellido)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaCliente", nombreParameter, apellidoParameter);
        }
    
        public virtual int BusquedaEmpleado(string nombre, string apellido)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaEmpleado", nombreParameter, apellidoParameter);
        }
    
        public virtual int BusquedaMarca(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaMarca", descripcionParameter);
        }
    
        public virtual int BusquedaModelo(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaModelo", descripcionParameter);
        }
    
        public virtual int BusquedaProducto(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaProducto", descripcionParameter);
        }
    
        public virtual int BusquedaProveedor(string nombre, string apellido)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaProveedor", nombreParameter, apellidoParameter);
        }
    
        public virtual int ListaCategoria()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaCategoria");
        }
    
        public virtual int ListaClientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaClientes");
        }
    
        public virtual int ListaEmpledos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaEmpledos");
        }
    
        public virtual int ListaMarca()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaMarca");
        }
    
        public virtual int ListaModelo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaModelo");
        }
    
        public virtual int ListaProductos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaProductos");
        }
    
        public virtual int ListaProveedores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaProveedores");
        }
    
        public virtual int BusquedaCategoria2(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaCategoria2", descripcionParameter);
        }
    
        public virtual int BusquedaCliente2(string nombre, string apellido)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaCliente2", nombreParameter, apellidoParameter);
        }
    
        public virtual int BusquedaEmpleado2(string nombre, string apellido)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaEmpleado2", nombreParameter, apellidoParameter);
        }
    
        public virtual int BusquedaMarca2(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaMarca2", descripcionParameter);
        }
    
        public virtual int BusquedaModelo2(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaModelo2", descripcionParameter);
        }
    
        public virtual int BusquedaProducto2(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaProducto2", descripcionParameter);
        }
    
        public virtual int BusquedaProveedor2(string nombre, string apellido)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaProveedor2", nombreParameter, apellidoParameter);
        }
    
        public virtual int ListaCategoria2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaCategoria2");
        }
    
        public virtual int ListaClientes2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaClientes2");
        }
    
        public virtual int ListaEmpledos2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaEmpledos2");
        }
    
        public virtual int ListaMarca2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaMarca2");
        }
    
        public virtual int ListaModelo2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaModelo2");
        }
    
        public virtual int ListaProductos2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaProductos2");
        }
    
        public virtual int ListaProveedores2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaProveedores2");
        }
    
        public virtual int BusquedaCategoria3(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaCategoria3", descripcionParameter);
        }
    
        public virtual int BusquedaCliente3(string nombre, string apellido)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaCliente3", nombreParameter, apellidoParameter);
        }
    
        public virtual int BusquedaEmpleado3(string nombre, string apellido)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaEmpleado3", nombreParameter, apellidoParameter);
        }
    
        public virtual int BusquedaMarca3(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaMarca3", descripcionParameter);
        }
    
        public virtual int BusquedaModelo3(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaModelo3", descripcionParameter);
        }
    
        public virtual int BusquedaProducto3(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaProducto3", descripcionParameter);
        }
    
        public virtual int BusquedaProveedor3(string nombre, string apellido)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaProveedor3", nombreParameter, apellidoParameter);
        }
    
        public virtual int ListaCategoria3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaCategoria3");
        }
    
        public virtual int ListaClientes3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaClientes3");
        }
    
        public virtual int ListaEmpledos3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaEmpledos3");
        }
    
        public virtual int ListaMarca3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaMarca3");
        }
    
        public virtual int ListaModelo3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaModelo3");
        }
    
        public virtual int ListaProductos3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaProductos3");
        }
    
        public virtual int ListaProveedores3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaProveedores3");
        }
    
        public virtual int BusquedaCategoria4(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaCategoria4", descripcionParameter);
        }
    
        public virtual int BusquedaCliente4(string nombre, string apellido)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaCliente4", nombreParameter, apellidoParameter);
        }
    
        public virtual int BusquedaEmpleado4(string nombre, string apellido)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaEmpleado4", nombreParameter, apellidoParameter);
        }
    
        public virtual int BusquedaMarca4(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaMarca4", descripcionParameter);
        }
    
        public virtual int BusquedaModelo4(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaModelo4", descripcionParameter);
        }
    
        public virtual int BusquedaProducto4(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaProducto4", descripcionParameter);
        }
    
        public virtual int BusquedaProveedor4(string nombre, string apellido)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaProveedor4", nombreParameter, apellidoParameter);
        }
    
        public virtual int ListaCategoria4()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaCategoria4");
        }
    
        public virtual int ListaClientes4()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaClientes4");
        }
    
        public virtual int ListaEmpledos4()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaEmpledos4");
        }
    
        public virtual int ListaMarca4()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaMarca4");
        }
    
        public virtual int ListaModelo4()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaModelo4");
        }
    
        public virtual int ListaProductos4()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaProductos4");
        }
    
        public virtual int ListaProveedores4()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaProveedores4");
        }
    
        public virtual int BusquedaCategoria5(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaCategoria5", descripcionParameter);
        }
    
        public virtual int BusquedaCliente5(string nombre, string apellido)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaCliente5", nombreParameter, apellidoParameter);
        }
    
        public virtual int BusquedaEmpleado5(string nombre, string apellido)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaEmpleado5", nombreParameter, apellidoParameter);
        }
    
        public virtual int BusquedaMarca5(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaMarca5", descripcionParameter);
        }
    
        public virtual int BusquedaModelo5(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaModelo5", descripcionParameter);
        }
    
        public virtual int BusquedaProducto5(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaProducto5", descripcionParameter);
        }
    
        public virtual int BusquedaProveedor5(string nombre, string apellido)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaProveedor5", nombreParameter, apellidoParameter);
        }
    
        public virtual int ListaCategoria5()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaCategoria5");
        }
    
        public virtual int ListaClientes5()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaClientes5");
        }
    
        public virtual int ListaEmpledos5()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaEmpledos5");
        }
    
        public virtual int ListaMarca5()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaMarca5");
        }
    
        public virtual int ListaModelo5()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaModelo5");
        }
    
        public virtual int ListaProductos5()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaProductos5");
        }
    
        public virtual int ListaProveedores5()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaProveedores5");
        }
    
        public virtual int BusquedaCategoria6(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaCategoria6", descripcionParameter);
        }
    
        public virtual int BusquedaCliente6(string nombre, string apellido)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaCliente6", nombreParameter, apellidoParameter);
        }
    
        public virtual int BusquedaEmpleado6(string nombre, string apellido)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaEmpleado6", nombreParameter, apellidoParameter);
        }
    
        public virtual int BusquedaMarca6(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaMarca6", descripcionParameter);
        }
    
        public virtual int BusquedaModelo6(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaModelo6", descripcionParameter);
        }
    
        public virtual int BusquedaProducto6(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaProducto6", descripcionParameter);
        }
    
        public virtual int BusquedaProveedor6(string nombre, string apellido)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BusquedaProveedor6", nombreParameter, apellidoParameter);
        }
    
        public virtual int ListaCategoria6()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaCategoria6");
        }
    
        public virtual int ListaClientes6()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaClientes6");
        }
    
        public virtual int ListaEmpledos6()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaEmpledos6");
        }
    
        public virtual int ListaMarca6()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaMarca6");
        }
    
        public virtual int ListaModelo6()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaModelo6");
        }
    
        public virtual int ListaProductos6()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaProductos6");
        }
    
        public virtual int ListaProveedores6()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaProveedores6");
        }
    
        public virtual int ListaCompra()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaCompra");
        }
    
        public virtual int ListaVentas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaVentas");
        }
    
        public virtual ObjectResult<BusquedaCategoria7_Result> BusquedaCategoria7(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BusquedaCategoria7_Result>("BusquedaCategoria7", descripcionParameter);
        }
    
        public virtual ObjectResult<BusquedaCliente7_Result> BusquedaCliente7(string nombre, string apellido)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BusquedaCliente7_Result>("BusquedaCliente7", nombreParameter, apellidoParameter);
        }
    
        public virtual ObjectResult<BusquedaEmpleado7_Result> BusquedaEmpleado7(string nombre, string apellido)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BusquedaEmpleado7_Result>("BusquedaEmpleado7", nombreParameter, apellidoParameter);
        }
    
        public virtual ObjectResult<BusquedaMarca7_Result> BusquedaMarca7(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BusquedaMarca7_Result>("BusquedaMarca7", descripcionParameter);
        }
    
        public virtual ObjectResult<BusquedaModelo7_Result> BusquedaModelo7(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BusquedaModelo7_Result>("BusquedaModelo7", descripcionParameter);
        }
    
        public virtual ObjectResult<BusquedaProducto7_Result> BusquedaProducto7(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BusquedaProducto7_Result>("BusquedaProducto7", descripcionParameter);
        }
    
        public virtual ObjectResult<BusquedaProveedor7_Result> BusquedaProveedor7(string nombre, string apellido)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BusquedaProveedor7_Result>("BusquedaProveedor7", nombreParameter, apellidoParameter);
        }
    
        public virtual ObjectResult<ListaCategoria7_Result> ListaCategoria7()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListaCategoria7_Result>("ListaCategoria7");
        }
    
        public virtual ObjectResult<ListaClientes7_Result> ListaClientes7()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListaClientes7_Result>("ListaClientes7");
        }
    
        public virtual ObjectResult<ListaCompra1_Result> ListaCompra1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListaCompra1_Result>("ListaCompra1");
        }
    
        public virtual int ListaEmpledos7()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ListaEmpledos7");
        }
    
        public virtual ObjectResult<ListaMarca7_Result> ListaMarca7()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListaMarca7_Result>("ListaMarca7");
        }
    
        public virtual ObjectResult<ListaModelo7_Result> ListaModelo7()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListaModelo7_Result>("ListaModelo7");
        }
    
        public virtual ObjectResult<ListaProductos7_Result> ListaProductos7()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListaProductos7_Result>("ListaProductos7");
        }
    
        public virtual ObjectResult<ListaProveedores7_Result> ListaProveedores7()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListaProveedores7_Result>("ListaProveedores7");
        }
    
        public virtual ObjectResult<ListaVentas1_Result> ListaVentas1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListaVentas1_Result>("ListaVentas1");
        }
    
        public virtual ObjectResult<ObterVentaEmpleado_Result> ObterVentaEmpleado(Nullable<int> idEmpleado)
        {
            var idEmpleadoParameter = idEmpleado.HasValue ?
                new ObjectParameter("IdEmpleado", idEmpleado) :
                new ObjectParameter("IdEmpleado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObterVentaEmpleado_Result>("ObterVentaEmpleado", idEmpleadoParameter);
        }
    
        public virtual ObjectResult<BusquedaVentaEmpleado_Result> BusquedaVentaEmpleado(string nombreEmplea, string apellidoEmplea)
        {
            var nombreEmpleaParameter = nombreEmplea != null ?
                new ObjectParameter("NombreEmplea", nombreEmplea) :
                new ObjectParameter("NombreEmplea", typeof(string));
    
            var apellidoEmpleaParameter = apellidoEmplea != null ?
                new ObjectParameter("ApellidoEmplea", apellidoEmplea) :
                new ObjectParameter("ApellidoEmplea", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BusquedaVentaEmpleado_Result>("BusquedaVentaEmpleado", nombreEmpleaParameter, apellidoEmpleaParameter);
        }
    
        public virtual ObjectResult<ListaEmpleados_Result> ListaEmpleados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListaEmpleados_Result>("ListaEmpleados");
        }
    
        public virtual ObjectResult<ObtenerCompraCliente_Result> ObtenerCompraCliente(Nullable<int> idCliente)
        {
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("IdCliente", idCliente) :
                new ObjectParameter("IdCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerCompraCliente_Result>("ObtenerCompraCliente", idClienteParameter);
        }
    
        public virtual ObjectResult<VentaActual_Result> VentaActual()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VentaActual_Result>("VentaActual");
        }
    
        public virtual ObjectResult<ObtenerCompraActualCliente_Result> ObtenerCompraActualCliente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerCompraActualCliente_Result>("ObtenerCompraActualCliente");
        }
    }
}
