//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIsEDM.ModeloUsuario
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AccesoUsuarioContainer : DbContext
    {
        public AccesoUsuarioContainer()
            : base("name=AccesoUsuarioContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FuncionDeAcceso> FuncionDeAccesoSet { get; set; }
        public virtual DbSet<FuncionAsignada> FuncionAsignadaSet { get; set; }
        public virtual DbSet<Usuario> UsuarioSet { get; set; }
    }
}
